Some fixes for errant data, modifications to best catch paths.
icykoneko/ff14-fish-tracker-app pull request #121
Opened 2022-05-23 23:56 UTC by nukes327

Some data fixes that have been sitting around waiting for enough to make a reasonable PR.

2022-05-28 02:23 UTC, icykoneko commented
Will get to this soon.

2022-05-30 20:09 UTC, icykoneko requested changes

2022-05-30 20:09 UTC, icykoneko commented on private/fishData.yaml
> +  intuitionLength: 360
I think this was correct.  350s = 2 Eorzean hours.

2022-05-30 20:11 UTC, icykoneko commented
LOL, you ended up grabbing the KO region data in this as well (re #122).  I'll double check it on my end, but it looked complete.

2022-05-30 22:52 UTC, nukes327 commented
If I remember correctly, Cinder Surprise's intuition starts at 6m and drops right after to 5m, which would mean 360s.

Let me find a file really quick to be sure.

2022-05-30 22:55 UTC, icykoneko commented
I dunno, TC doesn't appear to record it, or doesn't publicize it.  It just seemed to make more sense being 2 eorzean hours.

2022-05-30 23:03 UTC, nukes327 commented
There was a big debate in the fishcord discovery at one point about why it would be just longer than 2 hours yeah.

6 minute rollover is visible in [Fruity's video here:](https://youtu.be/2S1OHYIcZrk?t=140)
![firefox_2022-05-30_18-59-49](https://user-images.githubusercontent.com/10252242/171066381-74299355-bf04-4c2a-b38e-222589779817.png)

2022-05-30 23:05 UTC, icykoneko commented
Okay then.  Uhhh, that's the only issue I had with it.  Looks like you may need to rebase your branch though after my commit today.

2022-05-30 23:05 UTC, icykoneko approved these changes

2022-05-30 23:19 UTC, nukes327 commented
Think that should do it

2022-05-30 23:21 UTC, merged